# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5685f078592186d9c3e95576dc1397c00deba81f668e0dc3ad9c2c455753628962cf5e4b2294aa41521787a0c43dfe869243059b0b9588f40fed905297b677c6

test:
  secret_key_base: d5b5b383b087a1e6c362f2ed75a0138ff24a914920ee6bad54cec5c5565eff1eb778303eff7c492893521f21998a5225f8f8ebdfa1f601493cd31e585ee6f4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
